### PR TITLE
upgrade xlsx dependency to 0.19.3. yarn upgrade on all packages. Fix …

### PR DESCRIPTION
**Pull request by digital-codes**
…typescript errors in series.ts on std() and var() and in generic.ts. All to be checked

error on std and var are strange. both functions seem to be overloaded for number[] parameter but that version is never picked. Therefore type mismatch: returns number[], expected number.

### CODE REVIEW

**Review by vasylnrp — APPROVED** [review]

**Comment by digital-codes** [comment]
Anyone wants to merge this?

**Comment by vikasnair** [comment]
Can this be merged? The reliance on `xlsx` is a security issue which will be a mark on our SOC 2 audit, will have to drop this use of this package otherwise

**Comment by digital-codes** [comment]
This repo  has very little activity... unfortunately.

**Comment by steveoni** [comment]
@digital-codes if you can resolve the conflicts this will be merged

**Comment by digital-codes** [comment]
I see danfojs:dev has already upgrade of xlsx to xlsx-0.19.3. So this PR is no longer required when updating master from current dev.

**Comment by vikasnair** [comment]
When can we expect a new release that introduces this fix @steveoni?

**Pull request closed without merging**
