### PR TITLE
Add tf export to type definition

### PR DESCRIPTION
**Pull request by Devin345458**
Add tf export to type definition

### CODE REVIEW

**Comment by halflings** [comment]
You mentioned this PR in #332 ; can you explain how this solves that issue?
And can you apply the same change to the browser version of the library as well please? (the issue I'm encountering is in the browser, not node)

**Review by risenW — APPROVED** [review]

**Comment by risenW** [comment]
> You mentioned this PR in #332 ; can you explain how this solves that issue? And can you apply the same change to the browser version of the library as well please? (the issue I'm encountering is in the browser, not node)

This enforces that you use a single Tensorflow.js library, so you don't have to install a conflicting version.

**Comment by Devin345458** [comment]
@halflings  Basically instead of installing your own version of tensorflow via npm you can import the tensorflow installed via danfojs. My change just adds typescript/ide support for the import of tf from the danfojs package. I will make the change in the web pack but you can already

**Comment by risenW** [comment]
Fixed in latest Typescript version.

**Pull request closed without merging**
