### PR TITLE
[WIP] Add corr functions to DataFrame and Series.

### LINKED ISSUE #8: Corr function for Dataframe and Series
A Tensorflow based function to calculate Corr for series and columns, similar to Pandas Corr function.

### PR DESCRIPTION
**Pull request by JhennerTigreros**
# Description

Provide correlation method calculation to Series and DataFrame objects using built-in TFJS methods for operating with Tensors to improve performance on large data sets. 

Fixes #8 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] Align data dropping missing values.
- [x] Standard desviation methods.
- [x] Variance methods.
- [x] Series corr 
  - [x] Pearson.
  - [x] Kendall.
  - [x] Spearman.
- [ ] DataFrame corr 
  - [ ] Pearson.
  - [x] Kendall.
  - [ ] Spearman.
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Check compute performance in large datasets.
- [x] Compare results with Pandas computations in same datasets.

### CODE REVIEW

**Comment by steveoni** [comment]
@JhennerTigreros how are you? 

Are you still working on this PR?

**Comment by JhennerTigreros** [comment]
@steveoni Hi, sorry for the delay, a lot of things happen this year. I'm back to help on the project. Currently, I'm updating my branch and reading the new code to understand the new features and fixes 💪🏽

**Comment by JhennerTigreros** [comment]
I noticed out that we split the code in two different codebases. How can I proceed to apply this changes for both of them?

**Comment by risenW** [comment]
> @steveoni Hi, sorry for the delay, a lot of things happen this year. I'm back to help on the project. Currently, I'm updating my branch and reading the new code to understand the new features and fixes 💪🏽

@JhennerTigreros Welcome back! 🥳. We totally understand.

**Comment by risenW** [comment]
> I noticed out that we split the code in two different codebases. How can I proceed to apply this changes for both of them?

The reason for this is to properly separate functionality. Instead of writing and using a bunch of checks to switch between node and browser, we can just separate the projects and fully focus on each platform. That way, we both work faster, and also reduce the package size for each platform. 

The idea is to duplicate functions we have in the browser for node, although that does not stop you or anyone from adding platform-specific features.

**Comment by JhennerTigreros** [comment]
Hi @risenW, I understand the main idea behind this, but also I think we can do at better way and maybe avoid us from future work. Maybe using a notations in the functions to specify support from platforms, what do you think?

**Comment by risenW** [comment]
> Hi @risenW, I understand the main idea behind this, but also I think we can do at better way and maybe avoid us from future work. Maybe using a notations in the functions to specify support from platforms, what do you think?

Hey @JhennerTigreros Code structure has been updated to use a single base now. Also, TS rewrite is complete, so you’ll have to rebase.

**Comment by JhennerTigreros** [comment]
Heyyy @risenW, I will return to push new code and re structure the complete PR to support TS features.

**Comment by risenW** [comment]
Closing this as not active

**Pull request closed without merging**
