### PR TITLE
feat: Added `pctChange()` to DataFrame and `divNoNan()` to `$MathOps` in DataFrame

### PR DESCRIPTION
**Pull request by NeonSpork**
Structure is similar to `diff()` function, attempted to emulate the functionality from `pct_change()` function from pandas.

Chose to use camelcase naming here, thusly naming it `pctChange()`.

Added function to DataFrame interface.

Added `divNoNan()` from the tensorflow.js math operators to `$MathOps`. This was necessary to emulate the functionality from pandas, such that dividing by zero resulted in 0 not `Infinity`. Felt that this was a good addition regardless, seeing as it is one of the baseline math operators provided by tensorflow.js itself. As such it was trivial to add. Tensorflow docs here: [tf.divNoNan()](https://js.tensorflow.org/api/latest/#divNoNan) 

Added testing. Tests technically _work_ since they return the correct values, but the tests fail since JS is a little bit strange about floating point division.

A possible workaround is to choose calculations that will pass tests, since functionally `pctChange()` is working as expected.

### CODE REVIEW

**Comment by NeonSpork** [comment]
@risenW I can't quite seem to get the TensorFlow functions `div()` or `divNoNan()`. Since the actual functionality is working, I propose maybe working around it by choosing to use less wonky math in the tests?

**Comment by NeonSpork** [comment]
Worked around JavaScript's wonkiness in the tests by using divisions that perform more reliably.

**Comment by NeonSpork** [comment]
Resolves #383 in conjunction with PR #414

**Comment by risenW** [comment]
> Resolves #383 in conjunction with PR #414

Thanks, will review and test ASAP

**Comment by NeonSpork** [comment]
Added unit tests for `danfojs-browser`

**Comment by risenW** [comment]
@NeonSpork I just merged the diff PR, and there's a minor conflict here. Can you fix it, or do you want me to?

**Comment by NeonSpork** [comment]
> @NeonSpork I just merged the diff PR, and there's a minor conflict here. Can you fix it, or do you want me to?

Yea the merge conflicts are likely due to me adding the tests in the same spot in the test! I'll go through it and check right away

**Comment by NeonSpork** [comment]
Conflicts resolved and checks passed! 👍

**Pull request merged**
